package org.springdoclet

class Configuration {
  private static final String OPTION_DIRECTORY = '-d'
  private static final String OPTION_FILENAME = '-f'
  private static final String OPTION_STYLESHEET = '-stylesheet'
  private static final String OPTION_LINKPATH = '-linkpath'
  private static final String OPTION_FOOTER = '-footer'
  private static final String OPTION_TITLE = '-title'
  private static final String OPTION_RIGHTHEADER = '-right-header'
  private static final String OPTION_OVERVIEW_DIRECTORY = "-overview-directory"
  private static final String DEFAULT_DIRECTORY = '.'
  private static final String DEFAULT_FILENAME = './spring-summary.html'
  private static final String DEFAULT_STYLESHEET = './spring-summary.css'
  private static final String DEFAULT_LINKPATH = './'
  private static final String DEFAULT_FOOTER = "<p>Generated by <a href='http://scottfrederick.github.com/springdoclet/'>Spring Doclet</a></p>"
  private static final String DEFAULT_TITLE = "API Components"
  private static final String DEFAULT_RIGHTHEADER = ""

  String[][] options

  def getOutputDirectory() {
    getOption(OPTION_DIRECTORY) ?: DEFAULT_DIRECTORY
  }

  def getOutputFileName() {
    getOption(OPTION_FILENAME) ?: DEFAULT_FILENAME
  }

  def getStyleSheet() {
    getOption(OPTION_STYLESHEET) ?: DEFAULT_STYLESHEET
  }

  boolean isDefaultStyleSheet() {
    return getStyleSheet() == DEFAULT_STYLESHEET
  }

  def getLinkPath() {
    getOption(OPTION_LINKPATH) ?: DEFAULT_LINKPATH
  }

  def getFooter() {
    getOption(OPTION_FOOTER) ?: DEFAULT_FOOTER
  }

  def getTitle() {
    getOption(OPTION_TITLE) ?: DEFAULT_TITLE
  }

  def getRightHeader() {
    getOption(OPTION_RIGHTHEADER) ?: DEFAULT_RIGHTHEADER
  }

  def getOverviewDirectory() {
    getOption(OPTION_OVERVIEW_DIRECTORY) 
  }

  private String getOption(String optionName) {
    for (option in options) {
      if (option[0] == optionName) {
        return option[1]
      }
    }
    return null
  }

  int getOptionLength(option) {
    if (option.equals(OPTION_DIRECTORY)) {
      return 2
    } else if (option.equals(OPTION_FILENAME)) {
      return 2
    } else if (option.equals(OPTION_STYLESHEET)) {
      return 2
    } else if (option.equals(OPTION_LINKPATH)) {
      return 2
    } else if (option.equals(OPTION_FOOTER)) {
      return 2;
    } else if (option.equals(OPTION_TITLE)) {
      return 2;
    } else if (option.equals(OPTION_RIGHTHEADER)) {
      return 2;
    } else if (option.equals(OPTION_OVERVIEW_DIRECTORY)) {
      return 2;
    }
    return 0
  }
}
